version: '3.7'
services:

  # PHP & NodeJS Service
  app:
    build:
      context: .
    tty: true
    restart: unless-stopped
    working_dir: /programming-proficiency-test
    env_file:
      - .env
    volumes:
      - ${PWD}:/programming-proficiency-test
    ports:
      - '8080:8080'
